### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by CoreyHayward** [cntseesharp/L.AI#1]
This looks like a really interesting project. Would love to contribute and try it out but would only feel comfortable if the code was OS.

Is this planned to be Open Source or will it remain closed?

**Comment by cntseesharp** [comment]
Thank you for the feedback. I will release the source code in upcoming weeks, as soon as I add the features I'm lacking at the moment and do some code cleanup. Stay tuned.

**Comment by peterapps** [comment]
@cntseesharp I just came across this project and had the same thought, I'd really only feel comfortable if the code was open source. Have you decided whether or not you will open up the code?

**Comment by cntseesharp** [comment]
> @cntseesharp I just came across this project and had the same thought, I'd really only feel comfortable if the code was open source. Have you decided whether or not you will open up the code?

Hi. Thanks for your interest. I'm not planning on releasing the code anytime soon.

**Comment by cntseesharp** [comment]
@peterapps @CoreyHayward source code is now live
