### ISSUE TITLE
Limit the size of the prompt

### ISSUE THREAD

**Issue by bmpq** [cntseesharp/L.AI#3]
Need a setting to limit the prompt size, for example to only send the previous and next 10 lines. So the suggestion appears instantly and not in 5 seconds. Sometimes you don't need the entire file in the context.

**Comment by cntseesharp** [comment]
Noted. Will add as an option in the next release.

**Comment by cntseesharp** [comment]
@bmpq new update is out. Along with regular bug fixes, your post led me to find an issue that was overriding the Context Length setting. With a feature that automatically adjusts the generation prompt to fit the code in the context length, you can now adjust the amount of data sent to the API.

E.g. set "Context length" to 200 and only 200 tokens max, proportional to your positioning in the document, will be sent to the API.

![image](https://github.com/user-attachments/assets/148d3c94-c455-46ea-bcc0-5420424184db)
